### PR TITLE
Create ru_ru.json

### PR DESCRIPTION
**Pull request by mpustovoi**
Created ru_ru.json

### CODE REVIEW

**Comment by Hugman76** [comment]
Hi! Thank you for the contribution!
However, as said in the [contribution guide](https://github.com/DawnTeamMC/UniversalOres/blob/main/CONTRIBUTING.md#submitting-translations), localizations are managed on Crowdin!

**Comment by mpustovoi** [comment]
Done.

**Comment by mpustovoi** [comment]
The Russian localization was fully ready more than a year ago. Would you consider adding it?

**Comment by Hugman76** [comment]
It is added to the files I believe

**Comment by Hugman76** [comment]
Oh god, the translation filenames are all incorrectly capitalized. Not a single translation work. This affects all Dawn Team mods.

Looking into it!

**Comment by mpustovoi** [comment]
Oh, got it.
I assumed that Crowdin somehow automatically adds localization updates to the repository once in a while.

**Comment by Hugman76** [comment]
New v1.6.1 is rolling out to add translation files correctly. Thank you for pointing the issue out!

**Pull request closed without merging**
