### PR TITLE
Group recipes

### PR DESCRIPTION
**Pull request by Disketaa**

### CODE REVIEW

**Comment by Disketaa** [comment]
image
image
image

**Comment by Dhranios** [comment]
Translations are done via Crowdin:
https://crowdin.com/project/dawnteam

**Comment by Hugman76** [comment]
Like @Dhranios said, all translations are managed on [Crowdin](https://crowdin.com/project/dawnteam/ru). I can upload your file to the page directly if you do not want to do it yourself.
In any case, please remove the `ru_ru.json` file from the pull request so we can work out the recipe grouping thing.

**Comment by Disketaa** [comment]
Yup, upload please.

**Pull request closed without merging**
